# Generated by Django 3.0.4 on 2020-09-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='0', max_length=20)),
            ],
            options={
                'verbose_name': '筛选队列',
                'verbose_name_plural': '筛选队列',
                'db_table': 'queue',
            },
        ),
    ]
